name: Evaluate Invalidations

on: [push]

jobs:
  evaluate-invalidations:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1.0.0
      - name: Get package name
        id: info
        run: |
            REPONAME="${{ github.event.repository.name }}"
            PACKAGENAME=${REPONAME%.jl}
            echo "::set-output name=packagename::$PACKAGENAME"
      - uses: julia-actions/setup-julia@v1
        with:
          version: 'nightly'
      - name: Load package
        run: julia --project -e 'using ${{ steps.info.outputs.packagename }}'
